### ISSUE TITLE
[BUG] [go-feature-flag-web-provider]: API key is not passed to headers

### ISSUE THREAD

**Issue by yafanasiev** [open-feature/js-sdk-contrib#1029]
When using `feature-flags-relay-proxy` with API authorization enabled, passing `apiKey` to provider constructor is supposed to authorize all of the requests, but it does not. I believe the culprit is [here](https://github.com/open-feature/js-sdk-contrib/blob/main/libs/providers/go-feature-flag-web/src/lib/go-feature-flag-web-provider.ts#L273-L289) :

```js
    const headers = new Headers({
      'Content-Type': 'application/json',
      Accept: 'application/json',
    });
    if (this._apiKey) {
      headers.set('Authorization', `Bearer ${this._apiKey}`);
    }

    const init: RequestInit = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify(request),
    };
    const response = await fetch(endpointURL.toString(), init);
 ```
 
 `headers` object with correct authorization header is created, but is not used, instead using another header list without authorization.

**Comment by yafanasiev** [comment]
cc @thomaspoignant

**Comment by thomaspoignant** [comment]
Version `v0.2.1` is available https://www.npmjs.com/package/@openfeature/go-feature-flag-web-provider/v/0.2.1

**Comment by yafanasiev** [comment]
@thomaspoignant just tested the new version and it work perfectly. Thanks for getting to it so quickly!
