### ISSUE TITLE
Growthbook lodash.isempty not resolved

### ISSUE THREAD

**Issue by gvillo** [open-feature/js-sdk-contrib#1032]
## Introduction

I am trying to add OpenFeature growthbook provider into my vitejs project and I am getting this error. I don't see any "lodash.isempty" package in node_modules, any clues if I am doing something wrong or is the dependency is missing in pkg?

```
X [ERROR] Could not resolve "lodash.isempty"

    node_modules/@openfeature/growthbook-client-provider/index.esm.js:4:20:
      4 │ import isEmpty from 'lodash.isempty';
        ╵                     ~~~~~~~~~~~~~~~~

  You can mark the path "lodash.isempty" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.
```

Thanks!

**Comment by toddbaert** [comment]
@gvillo you're right! These deps are generated by NX automatically, but this subproject was missing the setting that does this. See my fix: https://github.com/open-feature/js-sdk-contrib/pull/1034

**Comment by marcoj** [comment]
I'm also getting this error. Looking forward for growthbook-client-provider 0.1.2 to be released 🥳
