### ISSUE TITLE
[flipt] Released version of @openfeature/flipt-web-provider does not support flipt entityId evaluation

### ISSUE THREAD

**Issue by ohyeahitsstef** [open-feature/js-sdk-contrib#1065]
The version of @openfeature/flipt-web-provider over at [npmjs.com](https://www.npmjs.com/package/@openfeature/flipt-web-provider) has outdated flipt dependencies.
Please release a version with updated flipt dependencies, to support flipt entityId evaluation.

The version in the open-feature/js-sdk-contrib repository has already an updated version of flipt-client-browser that supports entityId evaluation:
https://github.com/open-feature/js-sdk-contrib/blob/main/libs/providers/flipt-web

Thanks a lot!

**Comment by beeme1mr** [comment]
FYI, @markphelps. Are we good to release the updated web provider?

**Comment by markphelps** [comment]
@beeme1mr yes all good to release. i'll likely create another PR to upgrade to latest version of our browser SDK `v0.3.0` https://www.npmjs.com/package/@flipt-io/flipt-client-browser later today

**Comment by ohyeahitsstef** [comment]
Any update?

**Comment by markphelps** [comment]
@beeme1mr I believe the only thing required is to merge https://github.com/open-feature/js-sdk-contrib/pull/1098 ?

cc @ohyeahitsstef

**Comment by beeme1mr** [comment]
The latest version of the Flipt web provider has been released. Sorry for the delay.

**Comment by ohyeahitsstef** [comment]
Thanks!
