### ISSUE TITLE
GrowthBook server-side events not triggering rerenders

### ISSUE THREAD

**Issue by williamcarril** [open-feature/js-sdk-contrib#1114]
Hi, I've started using GrowthBook on some React projects and it seems that updates received from SSE events are not triggering rerenders.
I can see the events being received. If I remount the component, the new values are retrieved.
Is it  supposed to be supported?

**Comment by beeme1mr** [comment]
Hey @williamcarril, could you please try again using the latest version of the React SDK? [We recently](https://github.com/open-feature/js-sdk/pull/1095) released an update that may have solved this issue.
