### ISSUE TITLE
[flagd-provider] add unit test for zero-value resolutions from flagd

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk-contrib#165]
Flagd sends empty values in flag [response payloads](https://github.com/open-feature/schemas/blob/main/protobuf/schema/v1/schema.proto#L54) when the value is equivalent to the zero-value of the associated go type. We should test that this works as expected and still returns an equivalent zero-value (ie: `false`, `0`).

DoD:
- manual test confirming zero values are returned from the flagd provider when they are missing from the gRPC message (boolean set to false or numeric set to 0 in flagd config)
- new tests that assert correct values for zero-value flags

see: https://github.com/open-feature/flagd/issues/218

**Comment by odubajDT** [comment]
Hi I would like to work on this :)
