### ISSUE TITLE
Add ConfigCat provider

### ISSUE THREAD

**Issue by lukas-reining** [open-feature/js-sdk-contrib#327]
# Add ConfigCat provider

## Reasoning

I want to add an OpenFeature provider for ConfigCat. 
This would be valuable because we are using that system in our projects and would like to be able to interface it with OpenFeature.
I would like to implement it and contribute the provider to this repo.

## Requirements:

- [x] generate provider via [tooling](https://github.com/open-feature/js-sdk-contrib/blob/main/CONTRIBUTING.md#adding-a-module)
- [x] implement `Provider` interface
- [x] add tests
- [x] complete README
- [ ] add the new provider to the [OpenFeature docs](https://github.com/open-feature/openfeature.dev/issues/new/choose)

## Resources

- [ConfigCat](https://configcat.com/)

Keep in mind the CONTRIBUTING guidelines: https://github.com/open-feature/js-sdk-contrib/blob/main/CONTRIBUTING.md

**Comment by toddbaert** [comment]
Thanks @lukas-reining . If you'd like, I can add you to the org if you're interested.
