### ISSUE TITLE
OTel Span in flagd Provider

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/js-sdk-contrib#341]
The flagd provider should start an OTel span that will be passed to flagd to get cross-service tracing for evaluation.

**Comment by Kavindu-Dodan** [comment]
@toddbaert  I will attempt this as well :)

**Comment by toddbaert** [comment]
Sure think! Let me know if you need a hand!

**Comment by Kavindu-Dodan** [comment]
While JS samples work as a good starting point (grpc tracing with auto instrumentation [1] ), I was unable to get distributed traces for flagd. Same was true for a simple client (JS) - server(Java) and my assumption is something wrong with inter-lang contracts (baggage/propagation). 

I have reached otel contributors and will see how we can progress here.

[1] - https://www.npmjs.com/package/@opentelemetry/instrumentation-grpc

**Comment by Kavindu-Dodan** [comment]
open telemetry contributors are looking into the issue through https://github.com/open-telemetry/opentelemetry-js/issues/3775

**Comment by Kavindu-Dodan** [comment]
The fix at OTel JS was merged. Now, waiting for the next release

**Comment by Kavindu-Dodan** [comment]
I managed to finally validate this and can confirm that distributed traces work for flagd with JS when `GrpcInstrumentation` is enabled
