### ISSUE TITLE
Newest npm go-feature-flag-provider version incompatible with older NodeJS versions

### ISSUE THREAD

**Issue by mniehe** [open-feature/js-sdk-contrib#428]
@thomaspoignant just a heads up that the most recent change to the the JS `go-feature-flag-provider` [here](https://github.com/open-feature/js-sdk-contrib/commit/1a76aec01350cfab7c3324dcc5e15ea4e90e1462#diff-ee3cb7dbd197df1db128ec8577ed4071880f3019afd227280bbb438518db574eR123) used a feature (`structuredClone()`) that is [only available in NodeJS 17](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone) and above. This change will break builds for anyone who has the default value from `npm install` in their `package.json` (which is `"@openfeature/go-feature-flag-provider": "^0.5.8"`) and using a NodeJS version either 16 or below.

This should probably be considered a breaking change if not a in the NodeJS world.

For anyone who uses this and finds their build is randomly failing, you can just remove the `^` from the version in `package.json` to pin the version so it works for older NodeJS versions.

`"@openfeature/go-feature-flag-provider": "^0.5.8"` -> `"@openfeature/go-feature-flag-provider": "0.5.8"`

**Comment by thomaspoignant** [comment]
@mniehe good catch, this is not intended to make it compatible only with nodeJS 17 and upper.
I will open a pull request to replace the usage of `structuredClone()` with another solution.

**Comment by thomaspoignant** [comment]
Associated PR is available here https://github.com/open-feature/js-sdk-contrib/pull/429

**Comment by toddbaert** [comment]
@thomaspoignant maybe we should improve the CI by building/testing in a matrix of versions, or at least an older version (16) like we do in the SDK. If you agree I will create an issue for this.

**Comment by toddbaert** [comment]
> Thanks for the quick fix everyone! tada

:+1: nothing merged yet, but we'll keep you informed!

**Comment by thomaspoignant** [comment]
> @thomaspoignant maybe we should improve the CI by building/testing in a matrix of versions, or at least an older version (16) like we do in the SDK. If you agree I will create an issue for this.

I've opened a new issue for this #430.

**Comment by toddbaert** [comment]
> > @thomaspoignant maybe we should improve the CI by building/testing in a matrix of versions, or at least an older version (16) like we do in the SDK. If you agree I will create an issue for this.
> 
> I've opened a new issue for this #430.

see: https://github.com/open-feature/js-sdk-contrib/issues/428

**Comment by thomaspoignant** [comment]
@mniehe version `0.5.12` will fix your issue and will be soon available in npm.
