### ISSUE TITLE
Launch darkly provider fixes

### ISSUE THREAD

**Issue by sago2k8** [open-feature/js-sdk-contrib#444]
Hello everybody, don't really know if this is the correct process but we want to get launch darkly working for our frontend use case.

## problem:

There is a provider but there are couple of issues:
- the initialization proposed is outside the Provider which makes it hard to integrate and error prone.
- The library includes imports from `@openfeature/js-sdk` for types, prefered in this case should be `@openfeature/web-sdk`
- The provider seems to now work due the external initialisation, it seem to never get ready.

I opened a PR #418 that handles this issues, it has been tested in one of our frontend applications, the motivation for this change is basically to get the ball rolling and use the provider.

**Comment by toddbaert** [comment]
@sago2k8 Thanks for much for creating this issue.

As you've probably noticed, our web-sdk is still considered experimental. However, we are hoping to release a beta, and shortly after a 1.0 release soon (on the timescale of weeks, ideally). We did recently merged a fix for the SDK which could result in missing events in certain situations (see [here](https://github.com/open-feature/js-sdk/pull/472)) but the case is pretty narrow so I doubt it impacts you.

Regardless, I don't think the current implementation of the LD client provider supports some of the newer SDK features (events), and I suspect your PR brings significant value. Work like this will definitely help us move toward a confident 1.0 release!

I will review your PR today.

**Comment by sago2k8** [comment]
Great @toddbaert, lemme know if there is an issue I could help with to get the SDK to version 1.0.

Thank you.

**Comment by toddbaert** [comment]
> Great @toddbaert, lemme know if there is an issue I could help with to get the SDK to version 1.0.
> 
> Thank you.

This one certainly helps!

At the moment, the biggest hurdle for a 1.0 release is validating the static/dynamic context paradigm outlined [here](https://github.com/open-feature/spec/pull/171), which the web-sdk already adheres to. Your experience using the web SDK itself is probably valuable in itself.

**Comment by toddbaert** [comment]
This is resolved with https://github.com/open-feature/js-sdk-contrib/pull/418.

It will be released when https://github.com/open-feature/js-sdk-contrib/pull/467is merged.
