### ISSUE TITLE
[flagd] e2e test for flagd and flagd-web

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk-contrib#515]
This should be similar to what's in the js-sdk now.

Definition of done:
- run e2e tests based on test-harness [ghekin](https://github.com/open-feature/test-harness/blob/main/features/evaluation.feature) suite and flagd test image. A lot of the code can be taken from the [client](https://github.com/open-feature/js-sdk/tree/main/packages/client/e2e/step-definitions) and [server](https://github.com/open-feature/js-sdk/tree/main/packages/server/e2e/step-definitions) implementations in teh js-sdk.
- [run in CI](https://github.com/open-feature/js-sdk/blob/a4f7f5b1b8350f6a958d28b81b488018ca250fcc/.github/workflows/pr-checks.yaml#L64-L68)

**Comment by aepfli** [comment]
@toddbaert I think this is now also resolved, or am I missing something?
