### ISSUE TITLE
[go-feature-flag-web] Enable Secure Websocket Connection to Relay Proxy

### ISSUE THREAD

**Issue by adamgoose** [open-feature/js-sdk-contrib#624]
Currently, the provider forces the `ws` protocol, preventing secure connections to a relay proxy behind a reverse proxy.

https://github.com/open-feature/js-sdk-contrib/blob/8fac8cb902c8803200b3dbc74eace3d623746b4e/libs/providers/go-feature-flag-web/src/lib/go-feature-flag-web-provider.ts#L96
https://github.com/open-feature/js-sdk-contrib/blob/8fac8cb902c8803200b3dbc74eace3d623746b4e/libs/providers/go-feature-flag-web/src/lib/go-feature-flag-web-provider.ts#L105

In my environment, I've swapped `ws` with `wss` and removed the array of protocols passed to the `WebSocket` constructor, and the connection works as expected. I'm sure you'd want to either make this configurable or deterministic based on the protocol of the endpoint (http vs https).

**Comment by thomaspoignant** [comment]
@adamgoose thanks for raising this issue, I will provide a fix as soon as possible.
