### ISSUE TITLE
[FEATURE] Add new constructors to the `Error` classes that support error options

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk-contrib#713]
We should add constructors to the `Error` classes that support error options, to specifically support [cause](https://nodejs.org/api/errors.html#errorcause). This allows us to embed causal errors into rethrown errors. It's supported in browsers as well.

_Originally posted by @toddbaert in https://github.com/open-feature/js-sdk-contrib/pull/708#discussion_r1435639223_

**Comment by NeerajGartia21** [comment]
I would like to work on this issue. Can you please elaborate it a little bit more.

**Comment by toddbaert** [comment]
We need to support additional parameters to the Error classes in the SDK at `packages/shared/src/errors`. ES2022 supports this (node16+ and all modern browsers). We should add additional optional parameters or additional constructors that correspond to `ErrorOptions`, which will allow us to add a cause.

We will have to update our compiler options to ES2022 to support this.

Let me know if that makes it more clear and I will assign to you.

**Comment by NeerajGartia21** [comment]
It's more clear now. I can start working on this. Could you please assign it to me.
