### ISSUE TITLE
[flagd-in-process] Add targeting validation and log warning

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk-contrib#787]
The Go/in-process, Java/in-process and standalone versions of flagd log a warning message with invalid targeting rules when they are fetched. We should implement this in the JS/in-process.

Targeting rules can be validated with the [flags.json](https://flagd.dev/schema/v0/flags.json) schema in conjunction with the [targeting.json](https://flagd.dev/schema/v0/targeting.json) schema. Both will have to be loaded into AJV to fully validate. See similar examples in [Go](https://github.com/open-feature/flagd-schemas/blob/8c72c14eebff2a5b20fe2afb90c7ad44c1184ae8/json/flagd_definitions_test.go#L19-L25) and [Java](https://github.com/open-feature/java-sdk-contrib/blob/d468baeb4a54cc712ee95cb1a779c115da766033/providers/flagd/src/main/java/dev/openfeature/contrib/providers/flagd/resolver/process/model/FlagParser.java#L42-L57)

The in-process provider should be modified to use both of these schemas, and validate against them, only logging a warning if validation fails. Only a failure to parse the definition into a [FeatureFlag instance](https://github.com/open-feature/js-sdk-contrib/blob/d1f55342f8ded5123bf36ecf0fb97bb0b1aa85c0/libs/shared/flagd-core/src/lib/feature-flag.ts#L24-L29) should cause an abortive error (this means relaxing the existing validation to be consistent with all other impls which just do basic parsing).

**Comment by aepfli** [comment]
I am not sure if I understand this task correctly, but https://github.com/open-feature/js-sdk-contrib/blob/main/libs/shared/flagd-core/src/lib/parser.ts#L8 seems to me we're already doing validation, and only throw an exception if the property is set, else it is a warning.

Did I miss something here, @toddbaert? or should we do something differently?

**Comment by aepfli** [comment]
specifically due to https://github.com/open-feature/js-sdk-contrib/pull/878

**Comment by toddbaert** [comment]
You are right. I or somebody else must have done this!
