### ISSUE TITLE
flagd - bulk requesting every flag can result in a lot of flagd errors

### ISSUE THREAD

**Issue by klucsik** [open-feature/js-sdk-contrib#881]
As investigated in https://github.com/open-telemetry/opentelemetry-demo/pull/1515
the flagd-web-provider queries creates a lot of errors on flagd side.
In our setup backend and frontend flags are stored together. There are some targeted flags present, which needs context to evaluate their targeting. The bulk-querying doesn't provide any context, and queries flags which doesn't meant to be queried without context (or by the frontend at all). This results a lot of eval errors in flagd service.

**Comment by beeme1mr** [comment]
Hey @klucsik, thanks for letting me know. I'm looking into it.

**Comment by beeme1mr** [comment]
Resolved by https://github.com/open-feature/flagd/pull/1295
